# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHproto', '0003_auto_20170423_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='absent_excused',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_mark',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
    ]
