# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CHproto', '0006_auto_20170424_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='total_hours',
            new_name='hrs_per_mtg',
        ),
    ]
