# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CHproto', '0002_remove_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='course',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='teacher',
        ),
    ]
