# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHproto', '0004_auto_20170424_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='week_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
