# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHproto', '0005_attendance_week_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_hours',
            new_name='mtgs_per_week',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='total_hours',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_mark',
            field=models.CharField(choices=[('FULL', 'FULL'), ('TARDY', 'TARDY'), ('ABSENT', 'ABSENT')], max_length=8),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='tardy_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
